In [1]:
import keras

import matplotlib.pyplot as plt
import cv2
import numpy as np
import os

import random
import pickle

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten,MaxPooling2D,Conv2D

model_main=keras.models.load_model("model_multiclassification_final")
def predict_Video(frame):
    # try_data_path = path
    # try_data = cv2.imread(frame, cv2.IMREAD_GRAYSCALE)
    # Resizing the image and reshaping the image so it can pass the Convolutional Layer as a 4D arrays
    resized_try_data = cv2.resize(frame, (250, 250))
    try_data_resized = resized_try_data.reshape(1, 250, 250, 3)# Check the shape of the resized image arrays
    # print(try_data_resized.shape)

#     plt.imshow(try_data_resized[0], cmap='gray')
    # Declare the new data as Xnew
    Xnew = try_data_resized
    # make a prediction using the trained models
    ynew = model_main.predict(Xnew)
    print(ynew)
    return ynew
    # print(type(ynew[0])
    # show the predicted Outputs




In [2]:
import matplotlib as mpl
import matplotlib.cm as mtpltcm
cap=cv2.VideoCapture(0)
# cap_2=cv2.VideoCapture(0)
# cv2.setWindowProperty(cap_2,cv2.WINDOW_NORMAL)

font1 = cv2.FONT_HERSHEY_SIMPLEX
# org for the text being specified
org1 = (50, 50)
# font scale for the text being specified
fontScale1 = 0.8
# Blue color for the text being specified from BGR
color1 = ( 0 , 255 , 0 )
# Line thickness for the text being specified at 2 px
thickness1 = 2
# Using the cv2.putText() method for inserting text in the image of the specified path



while(cap.isOpened()):
    ret,frame=cap.read()
    frame=cv2.resize(frame,(250,250))
    colormap = mpl.cm.jet
    cNorm = mpl.colors.Normalize(vmin=0, vmax=255)
    scalarMap = mtpltcm.ScalarMappable(norm=cNorm, cmap=colormap)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        #add blur to make it more realistic
#         blur = cv2.GaussianBlur(gray,(15,15),0)
        #assign colormap
    colors = scalarMap.to_rgba(gray, bytes=False)

    cv2.imshow("Image",frame)
    cv2.imshow("Gray",colors)
    returned_result=predict_Video(frame)
    # print(returned_result)
    if np.argmax(returned_result,axis=1) == 1:
        cv2.putText(frame, 'Human Detected', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)
#         cv2.imshow('Image_2',colors)
        
    elif np.argmax(returned_result,axis=1) == 0:
        cv2.putText(frame, 'Chair', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)
    
    elif np.argmax(returned_result,axis=1) == 3:
        cv2.putText(frame, 'Sofa', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)
    
    
    elif np.argmax(returned_result,axis=1) == 2:
        cv2.putText(frame, 'Bed', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)
    
    
    elif np.argmax(returned_result,axis=1) == 4:
        cv2.putText(frame, 'Tabel', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)


    else:
        cv2.putText(frame, 'None Detected', org1, font1,
        fontScale1, color1, thickness1, cv2.LINE_AA)
        cv2.imshow("Image",frame)
        # print("Predicted=%s" % ('Not Detected'))

    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[1.9931844e-01 7.9265559e-01 5.0439802e-04 4.4292898e-04 7.0786700e-03]]
[[2.2714944e-01 7.6137704e-01 7.9624954e-04 7.5240870e-04 9.9248933e-03]]
[[0.21807912 0.76988673 0.00081512 0.00083419 0.01038489]]
[[0.24465404 0.7424028  0.00100793 0.00100085 0.01093446]]
[[0.26478752 0.7225883  0.00112886 0.00101862 0.01047666]]
[[0.27842328 0.70893943 0.00102335 0.00084085 0.01077312]]
[[0.24310905 0.74490684 0.00091462 0.00088729 0.01018226]]
[[0.24389699 0.74245155 0.00101551 0.00102901 0.01160697]]
[[0.25163266 0.7356851  0.00100313 0.00106472 0.0106144 ]]
[[0.2710037  0.7156243  0.00113218 0.00111126 0.01112855]]
[[0.2435231  0.7453998  0.00081273 0.00076328 0.00950112]]
[[2.3137200e-01 7.5907815e-01 6.8060064e-04 6.4823974e-04 8.2210219e-03]]
[[0.2928013  0.695779   0.00093824 0.00077569 0.00970582]]
[[0.32914954 0.65290135 0.00160293 0.00103387 0.01531232]]
[[0.5146299  0.45369923 0.00331752 0.00087702 0.02747635]]
[[0.46292722 0.46479547 0.00838116 0.00228702 0.06160924]]
[[0.5698685

[[0.19248067 0.71063197 0.03896291 0.02196177 0.03596273]]
[[0.17744033 0.72568905 0.0472581  0.02376891 0.02584358]]
[[0.18901548 0.728191   0.03763263 0.02037448 0.02478636]]
[[0.16742723 0.7507168  0.03585496 0.02030105 0.02569987]]
[[0.16360258 0.7475476  0.03749958 0.02138079 0.02996936]]
[[0.1936006  0.69552594 0.04885277 0.02889191 0.03312884]]
[[0.18221833 0.717176   0.04277742 0.0254149  0.03241326]]
[[0.17764995 0.7252326  0.05062247 0.02564673 0.02084822]]
[[0.16768807 0.74976856 0.03438764 0.02196249 0.02619326]]
[[0.2142451  0.7088315  0.02821716 0.0175538  0.03115255]]
[[0.29103994 0.58134335 0.02526048 0.01850056 0.08385568]]
[[0.24870837 0.6393372  0.0233206  0.0217349  0.06689899]]
[[0.26293746 0.61778647 0.02369469 0.02290931 0.07267208]]
[[0.27410972 0.5832253  0.02980656 0.03144298 0.08141541]]
[[0.29562384 0.5466357  0.03140938 0.03023763 0.09609356]]
[[0.2867347  0.5512181  0.0284068  0.03115443 0.10248598]]
[[0.33488822 0.46923658 0.04217951 0.04685037 0.10684523

[[0.19606969 0.10726181 0.18829612 0.28579557 0.22257686]]
[[0.19807573 0.10982364 0.20366815 0.27026483 0.21816763]]
[[0.22414313 0.08958667 0.20613451 0.21597306 0.26416257]]
[[0.23075797 0.16008545 0.21467663 0.19204794 0.20243189]]
[[0.25082448 0.21160619 0.17694086 0.15565434 0.20497417]]
[[0.24437957 0.34624276 0.13438255 0.11514454 0.15985061]]
[[0.25951183 0.41628507 0.10413185 0.08304005 0.13703114]]
[[0.27234966 0.40095916 0.10204732 0.08858877 0.13605504]]
[[0.27561945 0.47507992 0.08219437 0.06614537 0.1009609 ]]
[[0.23713829 0.5243103  0.07032234 0.05339365 0.11483548]]
[[0.271377   0.50895643 0.06745256 0.05508705 0.09712695]]
[[0.25894308 0.5037577  0.06727546 0.06512007 0.10490367]]
[[0.23272297 0.47525224 0.11084248 0.08574786 0.0954344 ]]
[[0.27536598 0.35691065 0.12333058 0.10544058 0.1389522 ]]
[[0.296613   0.4057179  0.10613257 0.07475729 0.11677919]]
[[0.20670879 0.4086311  0.12551546 0.08693005 0.17221455]]
[[0.22457515 0.2653779  0.13859357 0.1897123  0.18174118

[[0.22362016 0.23154594 0.09089112 0.1466187  0.3073241 ]]
[[0.21846227 0.2328652  0.09003513 0.1383284  0.32030898]]
[[0.2299306  0.24632925 0.10308834 0.1418284  0.27882347]]
[[0.23257992 0.2462228  0.09897666 0.13583376 0.28638682]]
[[0.23328583 0.23978783 0.09749601 0.13693267 0.29249766]]
[[0.2144035  0.26034626 0.09760736 0.13048999 0.29715285]]
[[0.21989326 0.24401566 0.08821585 0.1315255  0.3163497 ]]
[[0.22873111 0.26082566 0.08471607 0.12596406 0.29976305]]
[[0.21886264 0.25199285 0.08541178 0.12747085 0.31626192]]
[[0.21884479 0.25393403 0.0924277  0.12977955 0.30501384]]
[[0.22183883 0.25659496 0.08967974 0.1303977  0.3014888 ]]
[[0.2191774  0.27017534 0.08956305 0.12590718 0.29517704]]
[[0.22057055 0.2534703  0.09606469 0.13266577 0.2972287 ]]
[[0.21631694 0.26144475 0.09563683 0.13224731 0.29435417]]
[[0.22186458 0.2637821  0.09081943 0.12906599 0.2944679 ]]
[[0.21629977 0.26360765 0.08766964 0.12913036 0.30329257]]
[[0.20954113 0.2595531  0.09019277 0.13472803 0.30598497

[[0.19763236 0.09580468 0.11109321 0.1867128  0.40875694]]
[[0.2037276  0.09755114 0.11344482 0.18269098 0.4025855 ]]
[[0.1981484  0.09604779 0.11261887 0.18168017 0.4115048 ]]
[[0.1952486  0.09634411 0.11148866 0.18485974 0.41205886]]
[[0.19288397 0.09720495 0.11538716 0.1882526  0.40627134]]
[[0.19740342 0.09988482 0.11888663 0.19524653 0.38857853]]
[[0.19412012 0.09779729 0.12061433 0.19409257 0.39337572]]
[[0.18995048 0.09831517 0.11434672 0.18837595 0.40901163]]
[[0.19338563 0.09753118 0.11608324 0.18905036 0.4039496 ]]
[[0.19877514 0.09606403 0.11778606 0.19160974 0.39576504]]
[[0.1952734  0.10042332 0.11327326 0.18600339 0.40502667]]
[[0.1935134  0.10015073 0.11442024 0.19316153 0.39875412]]
[[0.19363329 0.10042394 0.1135876  0.18784206 0.4045131 ]]
[[0.19931738 0.09253638 0.10923771 0.18362749 0.415281  ]]
[[0.19227189 0.09614303 0.11241511 0.19358511 0.40558487]]
[[0.18576021 0.09952752 0.1141151  0.18799017 0.41260695]]
[[0.19481704 0.10076553 0.117612   0.18938754 0.39741787

[[0.18458974 0.1910855  0.16513914 0.21831782 0.24086773]]
[[0.22636375 0.2860083  0.13198537 0.14836875 0.20727383]]
[[0.245545   0.24306928 0.15134409 0.21563926 0.1444023 ]]
[[0.25980622 0.25058678 0.15143226 0.20558038 0.13259439]]
[[0.29065722 0.26323587 0.15120292 0.2026915  0.09221245]]
[[0.31600964 0.30924556 0.1900015  0.13849762 0.04624563]]
[[0.31323633 0.19591141 0.18916175 0.20712593 0.09456455]]
[[0.29214373 0.2063247  0.17909345 0.22012623 0.10231185]]
[[0.3389839  0.29234293 0.16218247 0.14582276 0.06066794]]
[[0.35126877 0.26660314 0.16336915 0.15960503 0.05915383]]
[[0.3548577  0.25156164 0.18680987 0.16091079 0.04585996]]
[[0.34083    0.3342031  0.1583918  0.12917699 0.03739816]]
[[0.29949254 0.27811447 0.19004118 0.17557247 0.05677935]]
[[0.22953619 0.31756127 0.19161195 0.19277933 0.06851123]]
[[0.2844121  0.2569662  0.19083484 0.17798723 0.08979964]]
[[0.32381254 0.25359848 0.15675335 0.16767249 0.09816314]]
[[0.2713593  0.2076895  0.17612655 0.17897733 0.16584739

[[0.27213377 0.24640879 0.22132237 0.17037475 0.08976042]]
[[0.2568156  0.23052041 0.22573784 0.19188775 0.09503834]]
[[0.29056016 0.2122489  0.20177698 0.19458173 0.1008322 ]]
[[0.2926012  0.21894042 0.20151293 0.18787743 0.09906805]]
[[0.27296478 0.22333965 0.20184667 0.1992619  0.10258704]]
[[0.2918666  0.14992404 0.1728677  0.1939274  0.19141425]]
[[0.28999916 0.10382993 0.14721009 0.18092503 0.2780359 ]]
[[0.19940272 0.1508565  0.16697888 0.24066804 0.24209382]]
[[0.22486192 0.13462615 0.16058202 0.230047   0.24988294]]
[[0.24421954 0.13056499 0.14422014 0.2398447  0.24115065]]
[[0.22223602 0.13857093 0.15581387 0.23244393 0.25093523]]
[[0.2362475  0.16090038 0.14955744 0.22871912 0.22457553]]
[[0.23336065 0.15371661 0.17631161 0.2370288  0.19958231]]
[[0.25556144 0.14392717 0.17883101 0.24732493 0.17435543]]
[[0.20786512 0.15260012 0.19801533 0.24990529 0.19161417]]
[[0.22076364 0.1451643  0.18496172 0.24641977 0.20269048]]
[[0.22755708 0.149431   0.16899624 0.2404035  0.21361221